### ISSUE TITLE
Incompatablity with kendo-ui

### ISSUE THREAD

**Issue by sjoerd222888** [ocombe/ocLazyLoad#120]
Kendo-ui seems to have some problem with ocLazyLoad. The angular directives of  kendo-ui do do not work lazy loaded with ocLazyLoad. I do not know whether this is an issue of ocLazyLoad or kendo-ui.

I have created a minimal example here: http://plnkr.co/edit/fK2rEKDDHxHZHmZ4sZCr?p=preview

You there see an input field that should become a date picker as described here:
http://demos.telerik.com/kendo-ui/datepicker/angular

There are no error messages and I have no clue where to search for issues.

**Comment by ocombe** [comment]
Hmm yes that's weird, it should work but it doesn't.
Do you know where I can find the source code from kendo ui unminified?

**Comment by sjoerd222888** [comment]
Unfortunately it is only available based on a commercial license I just learned... that's not so ideal.

**Comment by ocombe** [comment]
Ah, that's why I didn't find it...
It'll be hard to debug with the minified code, I'll try but I don't make any promises :)

**Comment by sjoerd222888** [comment]
I did (again) start a bounty on stackoverflow on this issue. Maybe someone familiar with kendo-ui is able to give some hints.

Link: http://stackoverflow.com/q/27544873/3737186

**Comment by ocombe** [comment]
Ok I think that I know what the problem is, kendo injects its own components all by himself, see this comment in the [kendo angular source code](https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.angular.js#L524) that will tell you everything:
`// caching $compile for the dirty hack upstairs. This is awful, but we happen to have elements outside of the bootstrapped root :(.`

I'll investigate a bit more to see how you can make this work, but it will probably require a bit of hacking.

**Comment by ocombe** [comment]
Ahh good news, I found the piece of code that is causing the problem: kendo ui declares its directives multiple times and there is a specific test in ocLazyLoad to prevent exactly this (because it's wrong wrong wrong !).
I need to see why they do that exactly, if that's a bug in their code or not. I'll keep the investigation!

**Comment by ocombe** [comment]
Ok this is fixed! It turns out that they are registering multiple directive with the same name but with different functions.
Don't do that in your code guys, it's stupid because you will make angular execute the directive wrappers multiple times and that's far from optimal.
But in the case of kendo they do that because they have automated the directive registering process and they only execute the differences when they register the directive a second time (the first registration is the generic stuff). Also they deal with aliases.
They probably should do that without registering the directive twice but go figure...

Anyway, it should work now !

**Comment by sjoerd222888** [comment]
Merci!

**Comment by PratibhaGajer** [comment]
hi..
I am loading modules dynamically using ocLazyload.js
actually i am registering multiple directive with the same name but with different functions because this is the big application and soo many developers are coding..they may create directives in their module of the same name which is already created by some other developer....so while running the application the directive which is registered first is executing but not others...
Is there any solution????

**Comment by sjoerd222888** [comment]
Maybe the easiest solution is to rename the directives such that there is no naming collision. If you are developing these directives within your company you should set up some naming conventions, some rules everybody should follow.

Alternatively you can do something similar to what KendoUi does (automated directive registration with only executing differences as mentioned by @ocombe). I would not recommend trying to go that path.
