### ISSUE TITLE
Error in karma testing

### ISSUE THREAD

**Issue by miganga** [ocombe/ocLazyLoad#122]
I am getting this error in Karma while testing

Error: [$injector:modulerr] Failed to instantiate module *** due to:
	Error: [$injector:modulerr] Failed to instantiate module oc.lazyLoad due to:
	No module found during bootstrap, unable to init ocLazyLoad

This is my angular init:

angular.module('***', [
		'oc.lazyLoad',
		'ui.router',
		'ngResource',
		'pascalprecht.translate',
		'ngAnimate',
		'ui.bootstrap',
		'tmh.dynamicLocale'
	])
	.run(function($rootScope, $state, $stateParams, $window) {

	});

**Comment by ocombe** [comment]
This is fix in the current master file (see #111), but there is no release for it yet.
Could you try the file in the current src folder and tell me if it's ok with you ?
I'll make a new release soon (fixing a bunch of stuff before).

**Comment by miganga** [comment]
Yes, just pass the first test :)

**Comment by dcorraldiaz** [comment]
I have the same problem in karma test execution.
I have tried to add the ocLazyLoad.js from src source, and does not fix the problem.

When executing tests, I test more than one application at the same time (because the continuous integration process must analize them together).
In order to get it, in unit test I'm pausing the bootstrap phase to avoid the apps bootstrap collision.
Maybe the problem is related to this?
http://code.angularjs.org/1.2.1/docs/guide/bootstrap#overview_deferred-bootstrap
(window.name = 'NG_DEFER_BOOTSTRAP!')

**Comment by ocombe** [comment]
Hmm yes that might be a problem. Is it possible to have a small test case somewhere?

**Comment by ocombe** [comment]
Anyway the new version I'm working on should throw a warning and not an error because I can't take all the use cases into account :)

**Comment by dcorraldiaz** [comment]
Sorry, but is complicated to write a small test.
I will wait for the next version of the lib.
Thanks.

**Comment by ocombe** [comment]
It should be fixed in 0.6.0!

**Comment by miganga** [comment]
great, thanks.  will check
