### ISSUE TITLE
Abitlity to define optional resources

### ISSUE THREAD

**Issue by hesamwls** [ocombe/ocLazyLoad#128]
Hi,
thanks for great work!
as i see, currently any failure in loading files, rejects the promise and as a result routing will be blocked.
it would be nice if we have notion of optional files which won't reject promise in case of failure.
is it doable?

**Comment by ocombe** [comment]
Hi,

it's a promise, so you should handle the rejection in the reject callback, isn't it possible ?

**Comment by hesamwls** [comment]
Hi,
ok, I don't feel too comfortable with promises! so help me.
you mean by returning some value in the next chain?
do I have enough information to decide whether rejection is caused by an optional or required file, there?

**Comment by ocombe** [comment]
Let's say that you load a file like this:

```js
$ocLazyLoad.load({
    name: 'TestModule',
    files: ['testModule.js']
});
```

You can use `then` to chain the load function:

```js
$ocLazyLoad.load({
    name: 'TestModule',
    files: ['testModule.js']
}).then(function success(data) {
  // it worked
}, function error(err) {
  // it failed
});
```

The second callback handles the error, and the parameter of this callback is a js Error object that contains the error message.
The error message should contain the url that failed, you can test it with a regex.
If you want, you can handle the rejection here. If you'd rather decide whether you'll stop here or continue, you can use the [`finally`](https://github.com/kriskowal/q/wiki/API-Reference#promisefinallycallback) function instead of `then`:

```
$ocLazyLoad.load({
    name: 'TestModule',
    files: ['testModule.js']
}).finally(function (data) {
  // it worked or failed, check data to see if it's a js error
});
```

**Comment by hesamwls** [comment]
ok, three things.
I applied ocLazyLoad in resolve property of router, so it's not only a matter of handling error. I have to resolve promise in case it is optional, but i think it's possible to resolve the returning promise in error callback.
but what if i have multiple optional and required files? does error message contain all information needed about all failed files or just the first one?
after all, I look at the code, and it seems to me, there shouldn't be much to add this feature.
all you need to do is to check if the failed file is optional or required in onerror event of <script> tag. (and resolve promise despite error if it is optional)
is'nt it a cleaner solution?
thanks by the way for your answer.

**Comment by ocombe** [comment]
First of all, the then function and finally function are both promises, you can return then to the resolve, so this should work.

Then yes I could add an option for optional files, but I'm not sure that it would be of much use to people. I won't add a new feature that you would be the only one to use...
The best way to do it then would be for you to define your own jsloader and handle the errors as you want.
You can copy the current one and change it for your own use.
The parameters are supplied to the loaders, so if you add new ones they should be given to your custom function.

The next major version of ocLazyLoad will have the loader as independent files so that you can use my own or not (you can already do that but you load a few kb of data for nothing).

**Comment by hesamwls** [comment]
fair enough.
thanks. you can close this issue.
