### ISSUE TITLE
Errors when loading Google Material using Dependency Injection.

### ISSUE THREAD

**Issue by heavysixer** [ocombe/ocLazyLoad#133]
I am happy to help debug this issue but it appears that there is some nested error which occurs when trying to load Google's Angular Material project in using ocLazyLoad. Here is what I see in the error console:

```
 ocLazyLoad.fileLoaded bower_components/angular-material/angular-material.css
angular.js:11607 ocLazyLoad.fileLoaded bower_components/angular-material/angular-material.js
angular.js:11607 ocLazyLoad.moduleLoaded material.components.whiteframe
angular.js:11607 ocLazyLoad.componentLoaded ["material.core.theming.palette", "constant", "$mdColorPalette"]
angular.js:11607 ocLazyLoad.moduleLoaded material.core.theming.palette
angular.js:11607 ocLazyLoad.componentLoaded ["material.core.theming", "directive", "mdTheme"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core.theming", "directive", "mdThemable"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core.theming", "provider", "$mdTheming"]
angular.js:11607 ocLazyLoad.moduleLoaded material.core.theming
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "constant", "$MD_THEME_CSS"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "factory", "$mdConstant"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "factory", "$mdMedia"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "factory", "$mdUtil"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "service", "$mdAria"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "service", "$mdCompiler"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "factory", "$mdGesture"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "factory", "$$MdGestureHandler"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "provider", "$$interimElement"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "factory", "$mdComponentRegistry"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "factory", "$mdInkRipple"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "directive", "mdInkRipple"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "directive", "mdNoInk"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "directive", "mdNoBar"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "directive", "mdNoStretch"]
angular.js:11607 ocLazyLoad.componentLoaded ["material.core", "invoke", "$provide"]
angular.js:11607 ocLazyLoad.moduleLoaded material.core
angular.js:11607 undefined is not a function
angular.js:11607 Error lazy loading config: undefined is not a function
```

The way I am lazy loading these modules is like this:

```
$ocLazyLoad.load({
      "name" : "ngMaterial",
      "files":["bower_components/angular-material/angular-material.css","bower_components/angular-material/angular-material.js"]
    });
```

The CSS is brought in and applied to the page even though the module loading fails. I am wondering if it is some part of a larger nested dependency which is not resolving correctly.

**Comment by ocombe** [comment]
Ok so I traced back the error all the way into angular material.

In the config function of material.core there is this line of code:
`$provide.decorator('$$rAF', ["$delegate", rAFDecorator]);`

It declares a decorator named "$$rAF", the problem is that a decorator only works if it is defined before the service it decorates and in this case it decorates $delegate which is part of angular and has already been instantiated...

I'm sorry but there is nothing I can do here, angular.material cannot be lazy loaded because of this. They might probably change their library for angular 1.5 because angular will make it possible to lazy load modules natively and they might have to change this behavior to make it possible (or maybe angular will make it possible to decorate existing services).

**Comment by ocombe** [comment]
@ajoslin can you confirm what I said above about the decorator ? I haven't used decorators that much and I'm not 100% sure of my explanation.
It's this line of angular material: https://github.com/angular/material/blob/master/src/core/core.js#L15

**Comment by heavysixer** [comment]
@ocombe no worries, actually I am totally impressed you were able to work your way back in the stack like that! I got lost in the guts of Angular but figured the problem was related to a race condition or something. I noticed some really weird module namespacing issues in the Material code. Thank you for taking the time to look through my bug report.

**Comment by ocombe** [comment]
Well my log function that reports errors isn't really helpful when the error comes from the module injected (it was defined to report errors from my lib, not another one), so you only got the error message "undefined is not a function" which isn't really helpful in this case, but I was able to get the full stack trace by throwing the error instead of just logging the error message :)

**Comment by JayKan** [comment]
@ocombe, 
I was experiencing a similar TypeError on loading angular-material, specifically relates to $$rAF decorator service. 

Here is my actual error: "$$rAF.throttle is not a function at new MdGesture". Based on your previous explanation, I traced back to MdGestureProvider (https://github.com/angular/material/blob/master/src/core/services/gesture/gesture.js), which I see $$raF service being injected into the MdGestureProvider.$get function. After that, I did global search from angular-material/src to look for the actual factory/service for $$rAF, but couldn't find any.

I've always thought that $provide.decorator('$$raF', function(){}) service will look up the existing '$$raF' service first and then return the delegated service. If '$$raF' server/factory doesn't exist, how can you still modify an existing service?

**Comment by salimchami** [comment]
+1. I have the same error...

**Comment by cecilpeng** [comment]
maybe the way to fix it is to decorate $$rAF before angular bootstraps.
angular.module('admin', [
    'ngAnimate',
    'angular-loading-bar',
    'config.lazyload'
])
.config(function($provide) {
    // fix bug: lazyload angular-material throws error 'TypeError: undefined is not a function'[actually $$rAF.throttle is undefined]
    $provide.decorator('$$rAF', ["$delegate", function rAFDecorator($delegate) {
        $delegate.throttle = function(cb) {
            var queueArgs, alreadyQueued, queueCb, context;
            return function debounced() {
                queueArgs = arguments;
                context = this;
                queueCb = cb;
                if (!alreadyQueued) {
                    alreadyQueued = true;
                    $delegate(function() {
                        queueCb.apply(context, queueArgs);
                        alreadyQueued = false;
                    });
                }
            };
        };
        return $delegate;
    }]);
})

**Comment by ocombe** [comment]
Sorry but it is impossible to lazy load Angular Animate (as well as probably any other official "angular" module), because they are too tightly coupled with Angular and they do some hardcore stuff inside angular itself when it starts (that it cannot do after that).

If you want to lazy load angular material you probably have to load those "official" libraries with your application.

I'm not sure about angular aria, but that's probably the same problem.

**Comment by cecilpeng** [comment]
Thanks for your suggestions which have to load those "official" libraries. Try to lazy load angular modules, is a great effort to manage packages. Some libraries enhance angular, eg, jQuery. Some libraries which use decorator are too tightly coupled with Angular. I can not agree more with your analysis:
```
It declares a decorator named $$rAF, the problem is that a decorator only works if it is defined before the service it decorates and in this case it decorates $delegate which is part of angular and has already been instantiated...
```

**Comment by websirnik** [comment]
I'm dealing with Angular Material lazy loading the following way. I've split the Angular material in junks. I've concatenated `core.js`,`default-theme.js` and a few modules that I need immediately in my app, and load them together with angular. The packages that I need later, I'm lazy loading through ocLazyLoad. 
Since Angular Material does not provide a way to build your own collection of modules, you need to do it yourself. I'm building my app with gulp & bower. You can use override options - https://github.com/ck86/main-bower-files#overrides-options to define the modules that you need.
