### ISSUE TITLE
Can I set headers when use native loader?

### ISSUE THREAD

**Issue by prugel** [ocombe/ocLazyLoad#143]

**Comment by ocombe** [comment]
You can set headers for the templates loader, but not for the js / css loaders. The files are loaded by appending script/link elements into the dom, that's why you can't use any headers. But you can disable cache with the param cache: false, it will add a timestamp to the url.
Templates on the other end are loaded via $http, so you can use any param that you'd use with $http.

**Comment by prugel** [comment]
thank you :)
