### ISSUE TITLE
Injecting angular 

### ISSUE THREAD

**Issue by ilbarzo** [ocombe/ocLazyLoad#155]
I have succesfully configured my app with $stateProvider routing for loading controllers on each route state.
Now I want to remove my app dependency from main module and inject them in the same way I do for controllers, is this possible??

an example of my working route:
```javascript
    $stateProvider.state("users", {
        url: "/admin/users",
        templateUrl: '/admin/users',
        resolve: {
            loadMyCtrl: ['$ocLazyLoad', function ($ocLazyLoad) {
                return $ocLazyLoad.load({
                    files: ['/app/controllers/admin/usersController.js', '/app/services/admin/usersService.js']
                });
            }]
        }
    });
```
I use the [textAngular](https://github.com/fraywing/textAngular) component succesfully if I define it as dependency of my module including scripts in main template:
```javascript
var app = angular.module('OrsoApp', ['ui.router', 'ngResource', 'ui.bootstrap', 'toaster', 'textAngular',
    'oc.lazyLoad']);
```
But if I remove it from there and try to load it into loadMyCtrl, I have an 'Unknown provider: taRegisterToolProvider' error.

best regards

**Comment by ocombe** [comment]
Angular will register the modules defined at bootstrap as dependencies of your main module.
If you include the file with the module textAngular in your page when you load your app, but you don't define it as a dependency for your app, then Angular will never register it.

ocLazyLoad will only register modules if you:
- load them with the load function
- call inject explicitly with the module name

Otherwise it will try to get the module from Angular, and in this case Angular never registered textAngular since it was not required by your app.

I could make this work, but right now it's not by default.

In the mean time, you can call inject like this (assuming you're using ocLazyLoad 1.x):

```js
    $stateProvider.state("users", {
        url: "/admin/users",
        templateUrl: '/admin/users',
        resolve: {
            loadTextAngular: ['$ocLazyLoad', function ($ocLazyLoad) {
                return $ocLazyLoad.inject('textAngular');
            }],
            loadMyCtrl: ['$ocLazyLoad', 'loadTextAngular', function ($ocLazyLoad, loadTextAngular) {
                return $ocLazyLoad.load({
                    files: ['/app/controllers/admin/usersController.js', '/app/services/admin/usersService.js']
                });
            }]
        }
    });
```

**Comment by ilbarzo** [comment]
Thanks ocombe, I understand.
But if I want to use the inject method as you suggest, how can I setup the textAngular module?
if I define it into $ocLazyLoadProvider.config as
```javascript
    $ocLazyLoadProvider.config({
        debug: true,
        modules: [{
            name: 'textAngular',
            files: ['/content/plugins/textangular/textAngular.css', '/content/plugins/textangular/textAngular-rangy.min.js', '/content/plugins/textangular/textAngular-sanitize.min.js', '/content/plugins/textangular/textAngular.min.js']
        }]
    });
```
I have this error: 'The module ""textAngular"" that you are trying to load does not exist. [$injector:nomod] Module 'textAngular' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.'

thanks for support!

**Comment by ocombe** [comment]
if you use inject it only works if the module is already available. You could use load if you did setup your module in the config:

```js
    $stateProvider.state("users", {
        url: "/admin/users",
        templateUrl: '/admin/users',
        resolve: {
            loadTextAngular: ['$ocLazyLoad', function ($ocLazyLoad) {
                return $ocLazyLoad.load('textAngular');
            }],
            loadMyCtrl: ['$ocLazyLoad', 'loadTextAngular', function ($ocLazyLoad, loadTextAngular) {
                return $ocLazyLoad.load({
                    files: ['/app/controllers/admin/usersController.js', '/app/services/admin/usersService.js']
                });
            }]
        }
    });
```

**Comment by ilbarzo** [comment]
but if I use load method I have an 'Unknown provider: taRegisterToolProvider <- taRegisterTool' error.
![image](https://cloud.githubusercontent.com/assets/2872864/6808054/42bf2d3e-d252-11e4-8835-8faa8069b004.png)

**Comment by kamilbrk** [comment]
I had exactly the same problem recently with textAngular. I just gave up and I am including TA in the main scripts bundle for the time being.

I think the problem *might* be related to separate Angular modules used in textAngular.js and textAngularSetup.js. Just haven't had time to investigate it further.

/sub

**Comment by ocombe** [comment]
If you load multiple files that depend on each other, you might have to use the parameter "serie: true" to make sure that they are loaded in the order that you define (load the file that define the module first, and then the files that use that module).
Or you could concatenate the files in one so that you'd only have to load one file, and everything should work with no problem.

If that's not the reason, could you make me a plunkr with the issue so that I can take a better look at it ?

**Comment by ilbarzo** [comment]
I have tried with the serie:true flag, and defining textAngular script as described in the related [doc](https://github.com/fraywing/textAngular/blob/master/README.md), but I have an 'Unknown Provider' error.
I have setup a [plunker](http://plnkr.co/edit/IbkvwatZxGFN5hy6eiPI?p=info), I use angular 1.3.14, ui-router 0.2.13 and TA 1.3.0.

**Comment by ocombe** [comment]
Thanks, I'll take a look at this but not until tomorrow night (I'm really busy today). It should be easy to fix with the plunkr

**Comment by ocombe** [comment]
Ok, here is the fixed version: http://plnkr.co/edit/ZlzUEEL0HArGac3Fjcig?p=preview
2 problems in your plunkr:
- don't reference files by "/url" but just "url" (relative path) in plunkr
- you just needed to make sure that the first resolve (the lib textAngular) was resolved before the controller, to do that you define the first resolve as a dependency for the second resolve. It was in the code that I gave you 2 days ago but you probably missed it because I didn't explained :)

**Comment by ilbarzo** [comment]
thanks ocombe, now I understand the right use of dependency in resolver!
but that something stange in your plnkr: in the first call of [preview](http://run.plnkr.co/plunks/ZlzUEEL0HArGac3Fjcig/#/test) in console log an error after textAngular load, then go straight to controller load and it works, but on page refresh it hangs on first provider error.
in my application this route is not the 'otherwise' one, and it stuck always on provider error. why?
best regards

**Comment by ocombe** [comment]
Ok I found the issue:
in the file textAngular.js, they bundle 2 modules: `textAngularSetup` & `textAngular`
The module `textAngularSetup` is defined first in the file, and uses a constant named `taRegisterTool`. This constant is defined in the module `textAngular`, BUT the module `textAngularSetup` does not declare the other module `textAngular` as a dependency.

So, the error is in textAngular, and it is clearly a bug that they should fix.

**Comment by WilliamKoza** [comment]
Thank you ocombe for this analyse. We can merge textAngularSetup & textAngular for resolve the problem : 

Add 

textAngular.constant('taRegisterTool', registerTextAngularTool);
textAngular.value('taOptions',  { 
...

Remove textAngularSetup form :

var textAngular = angular.module("textAngular", ['ngSanitize',  'textAngular.factories', 'textAngular.DOM', 'textAngular.validators', 'textAngular.taBind']);
