### ISSUE TITLE
$ocLazyLoadProvider.config() not loading modules defined in modules property

### ISSUE THREAD

**Issue by andymerskin** [ocombe/ocLazyLoad#17]
Hey guys,

I'm trying to use the `$ocLazyLoadProvider` in my app's config block to load in my modules during the `config` phase rather than `run`, but I'm finding that simply nothing is happening when I specify my modules in the config block, however the modules load just fine in the run block:

``` javascript
angular.module('myApp', ['oc.lazyLoad'])

    // Doesn't load the routes module:
    .config(function($ocLazyLoadProvider) {
        $ocLazyLoadProvider.config({
            asyncLoader: $script
            modules: [
                { name: "myApp.routes", files: ['modules/myApp.routes.js'] }
            ]
        });
    })

    // Works just fine, but since this module is configuring routes,
    // my app doesn't work properly at this point since config phase is passed:
    .run(function($ocLazyLoad) {
        $ocLazyLoad.load( { name: 'myApp.routes', files: ['modules/myApp.routes.js'] } );
    });
```

Any ideas why this wouldn't be loading my module during config?

Your help would be greatly appreciated! Thanks :)

**Comment by henrique-rotava** [comment]
@docmars, have you find a way to do that? I'm trying to do something like you and started at the same way (ocLazyLoad) and I didin't find yet another tool for that.

**Comment by docmars** [comment]
Hey @henrique-rotava. It's been a little while since I've taken a look at my particular problem. I think what I ended up doing was loading my JSON config using Deferred Angular Bootstrap, making them available as `constant`s, and then checking my route URL parameters (with an expected format) against the configuration in my `angular.run` block. It's not very pretty in my opinion, but it's working.

What is your use case? What are you trying to solve? Feel free to email me (listed on my profile), and I'd be happy to maybe provide some potential directions.
