### ISSUE TITLE
loading ngSanitizer fails

### ISSUE THREAD

**Issue by sjoerd222888** [ocombe/ocLazyLoad#176]
I am trying to use ng-bind-html and therefore require to load ngSaitizer (see https://code.angularjs.org/1.3.15/docs/api/ng/directive/ngBindHtml). Unfortunately my attempts with ocLazyLoad failed. I have created a question on stackoverflow (see http://stackoverflow.com/questions/30057005/oclazyload-error-using-ngsanitizer) and posted some code there  to reproduce the issue. I think it is a bug, but I am not 100% sure yet.

Thanks ;-)

**Comment by ocombe** [comment]
I think that this is not "lazyloadable" because Angular will check if it exists when it bootstraps your application, and if not then there is no way to enable it afterwards.

There is this problem for a few other "native" modules such as ngAnimate, ngRoute, ngTouch, ...
These modules are too tightly coupled with Angular and there is code within angular itself to check if they exist when the app is bootstrapped.

**Comment by sjoerd222888** [comment]
Ok. In this case the issue can be closed. There is nothing that can be done. Maybe it would be nice to have a list of modules which are 'officially unsupported'  for the documentation ;-).

**Comment by ocombe** [comment]
Yep that could be a good idea :)
You can edit the doc if you have the time, otherwise I'll do it when I think about it ;-)

**Comment by sjoerd222888** [comment]
I just tried to suggest a new page in the Advanced Usage chapter. But apparently I am only allowed to suggest changes on existing pages,.

**Comment by ocombe** [comment]
Add it to the FAQ, I'll make a new page later if needed :)

**Comment by sjoerd222888** [comment]
Done.

**Comment by ocombe** [comment]
Perfect thanks ! :+1:
