### ISSUE TITLE
How to access a given $xyzProvider of a lazy-loaded module?

### ISSUE THREAD

**Issue by bvahdat** [ocombe/ocLazyLoad#181]
Hi,

I'm in the middle of using the [following serviceprovider](https://github.com/bramski/angular-indexedDB#usage) which should be lazy-loaded inside a [hybrid-app](https://github.com/driftyco/ionic). Loading it through your library works like a charm, but then where and how can I access / dependency-inject `$indexedDBProvider` to configure my setup? I hope I'm wrong but I guess this is not possible with `ocLazyLoad` as `$indexedDBProvider` is not a service or directive etc. right?

**Comment by ocombe** [comment]
This is a good question. Yes, you can't access Providers outside config functions.
Here is how I would do it: instead of lazy loading just angular-indexedDB, I would lazy load a new module that would have angular-indexedDB as a dependency, and would have a config function where I would configure the provider.
In the end you would lazy load angular-indexedDB + your new module (you can use the [dependency injection](https://oclazyload.readme.io/v1.0/docs/dependency-injection) so that you would only load your new module), instead of just angular-indexedDB, and the new module's config phase would configure angular-indexedDB.

Is this clear ?

**Comment by bvahdat** [comment]
That was indeed the solution I came up with by myself as I was waiting for your answer. Awesome, thank you! :+1:

**Comment by ocombe** [comment]
Cool :)
Sorry, I was away this week end.
