### ISSUE TITLE
Directive usage : the example given in API doesn't work

### ISSUE THREAD

**Issue by aissaghouti** [ocombe/ocLazyLoad#210]
Hey,

I'm trying to load a directive in my template and it seems that the example of usage in the [documentation](https://oclazyload.readme.io/v1.0/docs/oclazyload-directive) doesn't work but the old way works.

It doesn't work:
```html
<div data-oc-lazy-load="{['FocusDirective.js','signin.html']}">
```
with the following error:
> Syntax Error: Token '' {1} at column {2} of the expression [{3}] starting at [{4}].

It works:
```html
<div data-oc-lazy-load="{name: 'focusMe', files: ['FocusDirective.js'], template: 'signin.html'}">
```

Here is my plunker : http://plnkr.co/edit/zbg1aZyETI6u0j12seFe?p=preview

**Comment by ocombe** [comment]
Ok got it, your using the syntax wrong, `{['FocusDirective.js','signin.html']}` is not valid js, you should either use the object (with the files property), or an array, or a string.

This is valid:
```js
<div data-oc-lazy-load="['FocusDirective.js']">
```
or
```js
<div data-oc-lazy-load="'FocusDirective.js'">
```

or
```js
<div data-oc-lazy-load="{files: ['FocusDirective.js']}">
```


As I told you in my tweet, you don't need to use the property `name`, and the property `template` won't do anything (it's deprecated).

Also in your case:
```js
<div data-oc-lazy-load="['FocusDirective.js','signin.html']">
```
makes no sense because you don't need to load `signin.html` from within the `signin` template file :) (but it will work anyway because the template is already in cache).

**Comment by aissaghouti** [comment]
Works perfectly fine, Thanks! Sorry for the inconvenience.

**Comment by ocombe** [comment]
No prob, always happy to help :)
