### ISSUE TITLE
Problems with $templateCache in oclazyload v.1.0.3 

### ISSUE THREAD

**Issue by webschik** [ocombe/ocLazyLoad#217]
Hi!

I'm using `ui-router` and `oclazyload 1.0.2` in my project.

````js
 .state('home.orders', {
            url: '^/orders?{type}',
            reloadOnSearch: false,
            template: '<div data-orders></div>',
            resolve: {
                loadModule: ["$ocLazyLoad", "$injector", ($ocLazyLoad, $injector) => {
                      return $ocLazyLoad.load('myModule');
                      
````

`myModule` contains some templates that are used in `data-orders` directive. After update `ocLazyLoad` to version 1.0.3 the templates are always loading from server and the next construction

````js
angular.module('myModule').run(['$templateCache', function($templateCache) {
debugger;
....
````

never runs

**Comment by ocombe** [comment]
Hmm, any change to have a plunkr for this please ? :)

**Comment by webschik** [comment]
http://plnkr.co/edit/IY36EA

See in console: `Error: [$compile:tpload] Failed to load template: template.html (HTTP status: 404 Not Found)`

**Comment by ocombe** [comment]
Thanks, I'll check it out asap

**Comment by ocombe** [comment]
Fixed in 1.0.4, thanks for the report !

**Comment by daominhsangvn** [comment]
I thought this issue was happen again.
It's not happen regularly but sometimes. Please see my pictures below with error and without error.
As you can see, the chunk files was loaded correctly.

The error:
![2016-09-19_9-53-03](https://cloud.githubusercontent.com/assets/8254183/18621575/7cb1162e-7e4f-11e6-8f13-83cc080deb5e.png)

The result it should be:
![2016-09-19_9-55-25](https://cloud.githubusercontent.com/assets/8254183/18621576/7cb1d280-7e4f-11e6-8508-102d41237895.png)

My route configuration
![2016-09-19_9-56-19](https://cloud.githubusercontent.com/assets/8254183/18621577/7cb38c56-7e4f-11e6-83a4-de105cedbfa0.png)

I'm using Angular 1.5.8, angular-ui-router 0.3.1, ocLazyLoad 1.0.9, Webpack 2.1.0-beta.21

**Comment by beORIGINAL** [comment]
I also have an issue similar to @daominhsangvn, but with Angular 1.6.0, angular-ui-router 0.3.2, ocLazyLoad 1.0.9, webpack 1.14.0 . It seems to me that rerun and reconfig works a bit incorrect with webpack(I've tried to use 1.0.4 but magic doesn't happen...)? And here - https://github.com/ocombe/ocLazyLoad/issues/89, @amaschas  also has  problems... We definitely believe in your soon fixes!)
