### ISSUE TITLE
Question: Load module from file in memory

### ISSUE THREAD

**Issue by Nadrendion** [ocombe/ocLazyLoad#230]
Hi, 

Im working on a large scale application and have the usage of loading modules on demand. This seems to be a great library for just that.

But - 

I fail to find any documentation of how to do what I think we need to do.
We have multiple sets of questions we want to ask our user depending on what the user has selected in a previous step.
What I am trying to avoid here is to load ALL sets of questions beforehand and not even request the files from the server where the services are defined. 

What I would like to do is to, based on the user choice, request the js-files from the server with $resource.get, and then load the module that is to be used into angularjs. 

Is this possible with this library or am I looking for something else?

**Comment by ocombe** [comment]
Yes that's exactly what this lib is for.
You can use the loader from the lib to load the files & automagically inject them, or load them yourself and call inject to make them available.
If you use $resource.get you will get the code of your services but you will have to call eval to execute it and then inject from my lib to make them available.
I advise you to simply use the load function from my lib (instead of using $resource), it will be simpler.

**Comment by Nadrendion** [comment]
aha! So the load-function takes not only a filename, but a url to a file? 
Great! I was not able to find this info in the documentation. I might just have read too fast perhaps.
