### ISSUE TITLE
Unable to configure a lazy loaded module

### ISSUE THREAD

**Issue by lcalvy** [ocombe/ocLazyLoad#238]
If you inject a module with ocLazyload, how to setup a configuration provider on this new module?

I try to inject a loopback angular module
https://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK

I need to access the LoopBackResourceProvider

``` javascript
angular.module('my-app-module').config(function(LoopBackResourceProvider) {

    // Use a custom auth header instead of the default 'Authorization'
    LoopBackResourceProvider.setAuthHeader('X-Access-Token');

    // Change the URL where to access the LoopBack REST API server
    LoopBackResourceProvider.setUrlBase('http://api.example.com/');
}
```

Is it possible?

**Comment by ocombe** [comment]
You should be able to define a config block in the files that you lazyLoad, but you cannot get access to the provider outside of that. Once the lib is lazy loaded it's too late. So if you need to configure anything include it in the list of files that you're lazy loading.

**Comment by lcalvy** [comment]
Thank you for quick answer.
Unfortunately I can't change this module, it's auto generated.
Any chance to configure ocLazyLoad ton inject a custom config function?

**Comment by ocombe** [comment]
You can lazy load multiples files at the same time, the lib and a custom file that you made yourself that contains the config. Just make sure that you use the parameter `serie: true` to load the lib first.
I'm not 100% sure that it will work though :)

**Comment by lcalvy** [comment]
Ok I will have a try but I don't understand how this custom file can have access to a module provider not already loaded?
I'm right?

**Comment by ocombe** [comment]
Well ocLazyLoad keep a reference on the providers when it registers them that's why it's able to register new components (those providers are only available during the config phase of Angular when you start the app, and when you register new components).
By keeping this reference you can register new components whenever you want, but if you loose the reference then there is no way to get it back. That's why ocLazyLoad can execute the config block with the right provider, but you cannot.
We could potentially make an update to the lib to give access to them, but it would probably result in weird bugs because it's really easy to do something wrong with it :)
