### ISSUE TITLE
Authorization Headers problem

### ISSUE THREAD

**Issue by juanmav** [ocombe/ocLazyLoad#276]
Hi,

I was trying to load a directive from a server with 'Authorization', The documentation says the following `If you load a template with the native template loader, you can use any parameter from the $http service (check: https://docs.angularjs.org/api/ng/service/$http#usage).`

```javascript
$ocLazyLoad.load('http://myserver/file.js', {
                 headers: {'Authorization': 'Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=='}
         }
);
```
Also tried before load set the Authorization:

```javascript
$http.defaults.headers.common.Authorization = 'Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==';
```
Any ideas?

Thanks in advance
JM

**Comment by ocombe** [comment]
The $http service is only used for templates (.html, .php, ...), not for js files.
This is how js files are loaded: https://github.com/ocombe/ocLazyLoad/blob/master/src/ocLazyLoad.loaders.common.js#L17
They are included into the dom as a <script> tag (that doesn't allow authorization headers). Could you maybe use cookies for that ?
Otherwise you can use requirejs or write your own js loader.

**Comment by juanmav** [comment]
Ok, my solution was to include credentials in the url.

```javascript
$ocLazyLoad.load('http://user:pass@myserver/file.js')
```
or my current solution

```javascript
$ocLazyLoad.load('http://user:pass@myserver/file.js?token=xxxxxxxxxxxxxxxxxx')
```
Thanks!!!!
JM

**Comment by ocombe** [comment]
Ah good :)

**Comment by ankryption** [comment]
@juanmav 
Sure your solution works but these parameters are visible In debugger's Network tab.
Such params cannot serve as security-tokens and must be avoided.
This is not as secure and a breach in security.

**Comment by juanmav** [comment]
@stack-amehta Thanks.... but you are two year late. :)
