### ISSUE TITLE
Rerun and Reconfig doesn´t work

### ISSUE THREAD

**Issue by gonzalec** [ocombe/ocLazyLoad#282]
I´m triying to use rerun/reconfig feature but this doesn't work with the ocLazyLoad version 1.0.9.

I noted that if you set cache:false the run and config blocks are executing everytime the module is loaded.

Sample config:
```
{
    name: 'moduleTask1',
    rerun: true,
    reconfig: true,
    files: [
      'module1.js'
    ]
}
```
See the [plunkr](https://plnkr.co/edit/BZ7M6q0xjmWZ0mEV6ACE)

**Comment by ocombe** [comment]
As expected, if you don't set "cache" to false then it won't reload files that have already been loaded, the promise will just resolve since the modules have already been loaded previously.
If there is a block of code that you want to reexecute then put it in a service and call it when you need but that's not what ocLazyLoad is for.
The rerun & reconfig options are here to execute "run" & "config" blocks whenever a new part of a module is loaded.
