### ISSUE TITLE
Load a directive using oc-lazyLoad

### ISSUE THREAD

**Issue by iankit3** [ocombe/ocLazyLoad#304]
Can i Lazy-Load a directive as in picture 
![1](https://cloud.githubusercontent.com/assets/9150788/15011975/93bb8a2e-1212-11e6-9d7c-d288cfd788af.png)
![2](https://cloud.githubusercontent.com/assets/9150788/15011979/98429024-1212-11e6-8391-31c282987f8f.png)

My code is not Modular so i want to lazy load the directive itself
Is it Possible ? Or i should make my code modular first and try lazyLoad the modules

**Comment by phuyem** [comment]
The goal of ocLazy is helping you "lazy load FILES" . Once you have loaded the js files, you can use any things from the files (Ctrl, directive... )

If you have just a few js files and small code base, don't bother with oclazy

**Comment by iankit3** [comment]
I have only one file with about 1500 lines of angular code , all in one controller Thats why I am asking to lazy load a directive instead 
Anyway Thanks  @phuyem

**Comment by giang12** [comment]
^ split those 1500 lines into their own respective files then. there are no magical ways to only pick X lines from a file from server. Or maybe im wrong, maybe you know the magic lol

**Comment by iankit3** [comment]
I think you haven't spent time in angular !  @giang12  Directives have a different life cycle ..
And splitting those 1500 codes that are in production in Not and Option (because there is something called  " TIME " ) 
I am working on someOne else's written code  , I hope you understand the concept of 'time' in my case

**Comment by giang12** [comment]
just gonna put this here https://scotch.io/tutorials/angularjs-best-practices-directory-structure
and you rather spending "Time" searching for a lazy, non-existent magic, rather than spending the "TIMe" to understand the code base to make it more efficient, you do you m8. See what approach save you more "Time", peace

**Comment by giang12** [comment]
well since your time is so damn precious, let's see directive life circle
1. .compile($element, ...)
2. .controller($element, $scope, ...)
3. .preLink($element, $scope, ...)
4. .link($element, $scope, ...)

split your 1500 lines (it's not that many really), into reusable parts -> load them via dependencies, in order...
eg: load necessary controller for a directive, then load the said directive -> that way the controller is reusable. damn that takes so much "time"

**Comment by giang12** [comment]
then you will ask, how to load in in order, damn im glad you ask...now you move into a module management...eg commonjs, or requirejs, or roll out your own...that will require more "time", so i guess you wont need them

**Comment by iankit3** [comment]
Hey ! I am very sorry if You felt offended @giang12  ! Really very sorry mate 
I took your words as Advice , actually I really am a NooB in Angular
So thank U very much (at least wasting for time for person like me )
I am sure it will help me in Future 

Thank You ! @giang12 I really mean it , man (I am very sorry)
Hope you understand  and Suggest me some places to get good grasp on these things if you want Please !
